import { ArrowRight, Info, Sparkles } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { ScrollView, Text, View } from 'react-native';
import Animated, { Easing, FadeInDown } from 'react-native-reanimated';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '@/components/Button';
import { DynamicPriorityCard } from '@/components/DynamicPriorityCard';
import { mockBeforeWitnessResults, mockWitnessPriorityResults } from '@/services/mockAIPriority';

export default function AIPriorityScreen() {
  const router = useRouter();
  const [witnessApplied, setWitnessApplied] = useState(false);
  const results = witnessApplied ? mockWitnessPriorityResults : mockBeforeWitnessResults;
  return <SafeAreaView className="flex-1 bg-background" edges={['top']}><ScrollView contentContainerClassName="px-5 pb-10" showsVerticalScrollIndicator={false}><Animated.View entering={FadeInDown.duration(450).easing(Easing.out(Easing.cubic))} className="pt-6"><View className="flex-row items-center gap-2"><View className="rounded-xl bg-navy p-2.5"><Sparkles stroke="#5EEAD4" size={19} /></View><Text className="text-xs font-bold uppercase tracking-[2px] text-teal">Aditya’s AI results</Text></View><Text className="mt-4 text-3xl font-bold text-navy">AI-Assisted Search Priority</Text><Text className="mt-3 text-base leading-6 text-muted">Decision support to help human teams choose where attention may be most useful next.</Text></Animated.View><Animated.View entering={FadeInDown.delay(100).duration(450)} className="mt-6 flex-row items-start gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4"><Info stroke="#2563EB" size={20} /><Text className="flex-1 text-sm font-semibold leading-5 text-navy">Search priority is decision support, not an exact location prediction.</Text></Animated.View><View className="mt-7 rounded-2xl border border-border bg-surface p-4"><View className="flex-row items-center justify-between"><Text className="text-sm font-bold text-navy">Evidence-driven update</Text><Text className="text-xs font-semibold text-teal">{witnessApplied ? 'New plan' : 'Awaiting evidence'}</Text></View><Text className="mt-2 text-sm leading-5 text-muted">NEW EVIDENCE {'→'} NEW PRIORITY {'→'} NEW SEARCH PLAN</Text>{witnessApplied ? <View className="mt-3 rounded-xl bg-amber-50 p-3"><Text className="text-sm font-semibold text-navy">New witness</Text><Text className="mt-1 text-sm leading-5 text-muted">“Child moving toward parking.”</Text></View> : null}<View className="mt-4"><Button label={witnessApplied ? 'Witness Applied' : 'Apply New Witness'} disabled={witnessApplied} fullWidth onPress={() => setWitnessApplied(true)} /></View></View><View className="mt-5 gap-3">{results.map((result, index) => <Animated.View key={`${result.zoneId}-${witnessApplied}`} entering={FadeInDown.delay(140 + index * 60).duration(360)}><DynamicPriorityCard result={result} changed={witnessApplied} /></Animated.View>)}</View><View className="mt-7 rounded-2xl border border-border bg-surface p-5"><Text className="text-base font-bold text-navy">Human review stays central</Text><Text className="mt-2 text-sm leading-5 text-muted">Signals can change the search plan, but they do not establish an exact location or identity. Volunteers and managers verify observations.</Text><View className="mt-5 gap-3"><Button label="Review Possible Match" icon={ArrowRight} iconPosition="right" fullWidth onPress={() => router.push('/possible-match')} /><Button label="Back to Search Zones" variant="outline" fullWidth onPress={() => router.replace('/main/search')} /></View></View></ScrollView></SafeAreaView>;
}
