import { AlertCircle, CheckCircle2, ShieldCheck } from 'lucide-react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { SafeAreaView, ScrollView, Text, View } from 'react-native';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { StatusBadge } from '@/components/StatusBadge';
import type { JoinErrorCode } from '@/services/joinCase';

export default function CasePreviewScreen() {
  const router = useRouter();
  const { token } = useLocalSearchParams<{ token?: string }>();
  const [error, setError] = useState<JoinErrorCode>();
  const value = token ?? '';
  const checkToken = (): JoinErrorCode | undefined => { const normalized = value.toLowerCase(); const nextError = normalized.includes('invalid') ? 'INVALID_QR' : normalized.includes('expired') ? 'EXPIRED_QR' : normalized.includes('unauthorized') ? 'UNAUTHORIZED' : normalized.includes('network') ? 'NETWORK_ERROR' : undefined; if (nextError) setError(nextError); return nextError; };
  if (error) return <SafeAreaView className="flex-1 bg-background"><View className="flex-1 items-center justify-center px-7"><View className="h-16 w-16 items-center justify-center rounded-full bg-red-50"><AlertCircle stroke="#DC2626" size={34} /></View><Text className="mt-5 text-2xl font-bold text-navy">{error === 'EXPIRED_QR' ? 'Invite expired' : error === 'UNAUTHORIZED' ? 'Not authorized' : error === 'NETWORK_ERROR' ? 'Network error' : 'Invalid invite'}</Text><Text className="mt-3 text-center text-base leading-6 text-muted">{error === 'NETWORK_ERROR' ? 'We could not reach the validation service. Try again later.' : 'This invite cannot be used to join the case. Ask the coordinator for a new authorized invite.'}</Text><View className="mt-7 w-full"><Button label="Try Again" fullWidth onPress={() => setError(undefined)} /></View><View className="mt-3 w-full"><Button label="Back to Join Case" variant="outline" fullWidth onPress={() => router.replace('/join-case')} /></View></View></SafeAreaView>;
  return <SafeAreaView className="flex-1 bg-background"><ScrollView contentContainerClassName="px-6 pb-10" showsVerticalScrollIndicator={false}><View className="pt-7"><Text className="text-xs font-bold uppercase tracking-[2px] text-teal">Invite preview</Text><Text className="mt-3 text-3xl font-bold text-navy">Review before joining</Text><Text className="mt-2 text-base leading-6 text-muted">This information is a preview. The backend must validate the secure invite before access is granted.</Text></View><Card className="mt-7"><View className="flex-row items-center gap-3"><View className="h-12 w-12 items-center justify-center rounded-xl bg-blue-50"><ShieldCheck stroke="#2563EB" size={24} /></View><View className="flex-1"><Text className="text-xs font-bold uppercase tracking-[1.5px] text-teal">Case</Text><Text className="mt-1 text-lg font-bold text-navy">North District Search</Text></View><StatusBadge status="LOCAL_SEARCH" compact /></View><View className="mt-6 gap-4 border-t border-border pt-4"><Row label="Status" value="Local search active" /><Row label="Authorized information" value="Zone assignments and verified updates" /><Row label="Eligibility" value="Pending backend validation" valueClass="text-warning" /></View></Card><Card className="mt-4 border-amber-100 bg-amber-50"><View className="flex-row items-start gap-2"><CheckCircle2 stroke="#D97706" size={18} /><Text className="flex-1 text-sm leading-5 text-muted">Only the secure invite token is passed forward. It is not treated as a trusted case identifier.</Text></View></Card><View className="mt-7 gap-3"><Button label="Join Case" fullWidth onPress={() => { const nextError = checkToken(); if (!nextError) router.replace('/join-confirmation'); }} /><Button label="Cancel" variant="outline" fullWidth onPress={() => router.back()} /></View></ScrollView></SafeAreaView>;
}
function Row({ label, value, valueClass = 'text-navy' }: { label: string; value: string; valueClass?: string }) { return <View className="flex-row items-start justify-between gap-4"><Text className="text-sm text-muted">{label}</Text><Text className={`flex-1 text-right text-sm font-semibold ${valueClass}`}>{value}</Text></View>; }
