import { ArrowRight, Clock3, MapPin, UserRound } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { StatusBadge } from '@/components/StatusBadge';
import { mockCaseDetail } from '@/services/mockCaseDetails';

export default function CaseDetailsScreen() {
  const router = useRouter();
  const item = mockCaseDetail;
  return <SafeAreaView className="flex-1 bg-background" edges={['top']}><ScrollView contentContainerClassName="px-5 pb-10" showsVerticalScrollIndicator={false}><View className="pt-5"><Text className="text-xs font-bold uppercase tracking-[2px] text-teal">Case details</Text><View className="mt-2 flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="text-3xl font-bold text-navy">{item.name}</Text><Text className="mt-2 text-sm text-muted">Active response case</Text></View><StatusBadge status={item.status} /></View></View><Card className="mt-6 overflow-hidden p-0"><View className="h-44 items-center justify-center bg-navy"><View className="h-20 w-20 items-center justify-center rounded-full bg-white/10"><UserRound stroke="#FFFFFF" size={37} /></View><Text className="mt-3 text-xs text-slate-300">Photo not available</Text></View><View className="flex-row divide-x divide-border p-4"><Metric label="Age" value={String(item.age)} /><Metric label="Gender" value={item.gender} /><Metric label="Priority" value={item.priority} critical={item.priority === 'Critical'} /></View></Card><Section title="Person"><InfoCard rows={[['Name', item.name], ['Age', String(item.age)], ['Gender', item.gender]]} /></Section><Section title="Last seen"><InfoCard rows={[["Location", item.location], ['Time', item.lastSeenTime], ['Direction', item.direction]]} /></Section><Section title="Description"><InfoCard rows={[["Clothing", item.clothing], ['Physical description', item.physicalDescription], ['Known destination', item.knownDestination]]} /></Section><Section title="Search status"><Card><View className="flex-row items-center justify-between"><Text className="text-base font-bold text-navy">Search progress</Text><Text className="text-lg font-bold text-teal">{item.searchProgress}%</Text></View><View className="mt-3 h-2 rounded-full bg-background-muted"><View className="h-full rounded-full bg-teal" style={{ width: `${item.searchProgress}%` }} /></View><View className="mt-5 flex-row justify-between"><Stat label="Volunteers" value={item.volunteerCount} /><Stat label="Evidence" value={item.evidenceCount} /><Stat label="Zones complete" value={`${item.completedZones}/${item.searchZones}`} /></View></Card></Section><Section title="Search zones"><InfoCard rows={[["Total zones", String(item.searchZones)], ['Completed', `${item.completedZones} zones`], ['Current priority', item.priority]]} /></Section><Section title="Evidence"><InfoCard rows={[["Verified evidence", `${item.evidenceCount} submissions`], ['Latest review', 'Human verification in progress']]} /></Section><View className="mt-8"><Button label="View Case Timeline" icon={ArrowRight} iconPosition="right" fullWidth onPress={() => router.push('/case-timeline')} /></View></ScrollView></SafeAreaView>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View className="mt-7"><Text className="mb-3 text-lg font-bold text-navy">{title}</Text>{children}</View>; }
function InfoCard({ rows }: { rows: string[][] }) { return <Card className="gap-3">{rows.map(([label, value]) => <View key={label} className="flex-row items-start justify-between gap-4"><Text className="text-sm text-muted">{label}</Text><Text className="flex-1 text-right text-sm font-semibold text-navy">{value}</Text></View>)}</Card>; }
function Metric({ label, value, critical }: { label: string; value: string; critical?: boolean }) { return <View className="flex-1 items-center"><Text className="text-xs text-muted">{label}</Text><Text className={`mt-1 text-sm font-bold ${critical ? 'text-danger' : 'text-navy'}`}>{value}</Text></View>; }
function Stat({ label, value }: { label: string; value: number | string }) { return <View><Text className="text-xs text-muted">{label}</Text><Text className="mt-1 text-lg font-bold text-navy">{value}</Text></View>; }
