import { AlertTriangle, Check, FileCheck2, HelpCircle, RotateCcw, UserRound, X } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { Alert, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { mockPossibleMatch } from '@/services/mockPossibleMatch';
import type { MatchReviewAction } from '@/services/possibleMatch';

export default function PossibleMatchScreen() {
  const router = useRouter();
  const confirmAction = (action: MatchReviewAction) => { const labels = { CONFIRM: 'Confirm possible match', REJECT: 'Reject possible match', REQUEST_REVIEW: 'Request human review' }; Alert.alert(labels[action], 'This action will be prepared for the future review service. Human verification remains required.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Continue', style: action === 'REJECT' ? 'destructive' : 'default', onPress: () => router.back() }]); };
  return <SafeAreaView className="flex-1 bg-background" edges={['top']}><ScrollView contentContainerClassName="px-5 pb-10" showsVerticalScrollIndicator={false}><View className="pt-6"><Text className="text-xs font-bold uppercase tracking-[2px] text-teal">Human review</Text><Text className="mt-2 text-3xl font-bold text-navy">Possible Match</Text><Text className="mt-2 text-base leading-6 text-muted">A signal requires careful review by an authorized manager.</Text></View><Card className="mt-6 border-red-100 bg-red-50"><View className="flex-row items-center gap-3"><AlertTriangle stroke="#DC2626" size={24} /><Text className="flex-1 text-base font-bold text-danger">HUMAN VERIFICATION REQUIRED</Text></View><Text className="mt-3 text-sm leading-5 text-muted">This is not an identity confirmation. AI does not independently confirm a person’s identity.</Text></Card><Card className="mt-4 overflow-hidden p-0"><View className="h-48 items-center justify-center bg-navy"><View className="h-20 w-20 items-center justify-center rounded-full bg-white/10"><UserRound stroke="#FFFFFF" size={38} /></View><Text className="mt-3 text-xs text-slate-300">Candidate image not provided</Text></View><View className="p-5"><Text className="text-base font-bold text-navy">Candidate image</Text><Text className="mt-1 text-sm text-muted">Displayed only when supplied by the backend.</Text>{mockPossibleMatch.similarity !== undefined || mockPossibleMatch.confidence !== undefined ? <View className="mt-4 flex-row gap-4"><Score label="Similarity" value={mockPossibleMatch.similarity} /><Score label="Confidence" value={mockPossibleMatch.confidence} /></View> : null}</View></Card><Section title="Evidence" icon={FileCheck2}>{mockPossibleMatch.evidence.map((item) => <Bullet key={item} text={item} />)}</Section><Section title="Observations" icon={HelpCircle}>{mockPossibleMatch.observations.map((item) => <Bullet key={item} text={item} />)}</Section><View className="mt-5 flex-row items-center gap-2"><RotateCcw stroke="#64748B" size={15} /><Text className="text-xs text-muted">Received {mockPossibleMatch.timestamp}</Text></View><View className="mt-7 gap-3"><Button label="Confirm" icon={Check} fullWidth onPress={() => confirmAction('CONFIRM')} /><Button label="Reject" icon={X} variant="danger" fullWidth onPress={() => confirmAction('REJECT')} /><Button label="Request Review" icon={HelpCircle} variant="outline" fullWidth onPress={() => confirmAction('REQUEST_REVIEW')} /></View></ScrollView></SafeAreaView>;
}
function Section({ title, icon: Icon, children }: { title: string; icon: typeof FileCheck2; children: React.ReactNode }) { return <View className="mt-7"><View className="mb-3 flex-row items-center gap-2"><Icon stroke="#0D9488" size={18} /><Text className="text-lg font-bold text-navy">{title}</Text></View><Card className="gap-3">{children}</Card></View>; }
function Bullet({ text }: { text: string }) { return <View className="flex-row items-start gap-3"><View className="mt-2 h-1.5 w-1.5 rounded-full bg-teal" /><Text className="flex-1 text-sm leading-5 text-muted">{text}</Text></View>; }
function Score({ label, value }: { label: string; value?: number }) { return <View><Text className="text-xs text-muted">{label}</Text><Text className="mt-1 text-lg font-bold text-navy">{value !== undefined ? `${value}%` : 'Not provided'}</Text></View>; }
