import { BellRing, ChevronRight, MapPin } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Card } from '@/components/Card';
import { BackButton } from '@/components/BackButton';
import { StatusBadge } from '@/components/StatusBadge';
import { mockPublicCases, mockPublicSearchAlert } from '@/services/mockPublicSearch';

export default function PublicCaseFeedScreen() {
  const router = useRouter();
  return <SafeAreaView className="flex-1 bg-background" edges={['top']}><ScrollView contentContainerClassName="px-5 pb-10" showsVerticalScrollIndicator={false}><View className="pt-5"><BackButton fallbackRoute="/landing" variant="ghost" className="mb-3" /><Text className="text-xs font-bold uppercase tracking-[2px] text-teal">Public Search</Text><Text className="mt-2 text-3xl font-bold text-navy">Public Search</Text><Text className="mt-2 text-base text-muted">Help with authorized community searches.</Text></View><Card className="mt-6 border-blue-100 bg-blue-50" onPress={() => router.push('/public-search-alert')}><View className="flex-row items-start gap-3"><View className="rounded-xl bg-blue p-2.5"><BellRing stroke="#FFFFFF" size={20} /></View><View className="flex-1"><Text className="text-base font-bold text-navy">{mockPublicSearchAlert.title}</Text><Text className="mt-1 text-sm leading-5 text-muted">{mockPublicSearchAlert.message}</Text><Text className="mt-3 text-xs font-semibold text-blue">{mockPublicSearchAlert.updatedAt}</Text></View><ChevronRight stroke="#2563EB" size={19} /></View></Card><View className="mt-8"><Text className="mb-3 text-lg font-bold text-navy">Authorized cases</Text>{mockPublicCases.map((item) => <Card key={item.name} onPress={() => router.push('/public-case-details')} className="mb-3"><View className="flex-row items-start justify-between gap-3"><View className="flex-1"><Text className="text-lg font-bold text-navy">{item.name}</Text><Text className="mt-1 text-sm text-muted">Age {item.age}</Text></View><StatusBadge status={item.status} compact /></View><View className="mt-4 gap-2 border-t border-border pt-3"><View className="flex-row items-center gap-2"><MapPin stroke="#64748B" size={15} /><Text className="flex-1 text-sm text-muted">{item.lastKnownArea}</Text></View><Row label="Last seen" value={item.lastSeen} />{item.priority ? <Row label="Priority" value={item.priority} valueClass={item.priority === 'Critical' ? 'text-danger' : 'text-warning'} /> : null}</View><View className="mt-4 flex-row items-center"><Text className="text-sm font-semibold text-blue">View Case</Text><ChevronRight stroke="#2563EB" size={15} /></View></Card>)}</View><Text className="mt-5 text-center text-xs leading-5 text-muted">Public Search shares only authorized information. All reports require human verification.</Text></ScrollView></SafeAreaView>;
}

function Row({ label, value, valueClass = 'text-navy' }: { label: string; value: string; valueClass?: string }) { return <View className="flex-row justify-between gap-4"><Text className="text-xs text-muted">{label}</Text><Text className={`flex-1 text-right text-xs font-semibold ${valueClass}`}>{value}</Text></View>; }
