import { CameraView, useCameraPermissions } from 'expo-camera';
import { ArrowLeft, Flashlight, FlashlightOff, ScanLine } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, SafeAreaView, Text, View } from 'react-native';
import { Button } from '@/components/Button';
import { PermissionCard } from '@/components/PermissionCard';

export default function QRScannerScreen() {
  const router = useRouter();
  const [permission, requestPermission] = useCameraPermissions();
  const [flash, setFlash] = useState(false);
  const [scanned, setScanned] = useState(false);
  const [error, setError] = useState('');
  if (!permission) return <SafeAreaView className="flex-1 bg-navy" />;
  if (!permission.granted) return <SafeAreaView className="flex-1 justify-center bg-background px-6"><ScanLine stroke="#2563EB" size={36} /><Text className="mt-5 text-center text-xl font-bold text-navy">Camera access needed</Text><Text className="mt-2 text-center text-base leading-6 text-muted">Allow access before scanning a secure case invite.</Text><View className="mt-6"><PermissionCard kind="camera" state={permission.canAskAgain ? 'not-requested' : 'blocked'} onRequest={requestPermission} /></View><Pressable accessibilityRole="button" accessibilityLabel="Cancel camera scanner" className="mt-4 items-center" onPress={() => router.back()}><Text className="font-semibold text-blue">Cancel</Text></Pressable></SafeAreaView>;
  const handleScan = ({ data }: { data: string }) => { if (scanned) return; setScanned(true); setError(''); const normalized = data.toLowerCase(); if (normalized.includes('invalid')) setError('This QR invite is invalid.'); else if (normalized.includes('expired')) setError('This QR invite has expired.'); else if (normalized.includes('unauthorized')) setError('You are not authorized to use this invite.'); else if (normalized.includes('network')) setError('Network error. Try again when connected.'); else router.push({ pathname: '/case-preview', params: { token: data } }); };
  return <View className="flex-1 bg-navy"><CameraView className="flex-1" facing="back" enableTorch={flash} barcodeScannerSettings={{ barcodeTypes: ['qr'] }} onBarcodeScanned={scanned ? undefined : handleScan}><SafeAreaView className="flex-1 justify-between"><View className="flex-row items-center justify-between px-5 pt-4"><Pressable accessibilityLabel="Cancel scanner" accessibilityRole="button" className="rounded-xl bg-black/40 p-3" onPress={() => router.back()}><ArrowLeft stroke="#FFFFFF" size={21} /></Pressable><Pressable accessibilityLabel={flash ? 'Turn flash off' : 'Turn flash on'} accessibilityRole="button" className="rounded-xl bg-black/40 p-3" onPress={() => setFlash((value) => !value)}>{flash ? <FlashlightOff stroke="#FFFFFF" size={21} /> : <Flashlight stroke="#FFFFFF" size={21} />}</Pressable></View><View className="items-center"><View className="h-64 w-64 rounded-3xl border-2 border-white"><View className="absolute -left-1 -top-1 h-8 w-8 border-l-4 border-t-4 border-teal-light" /><View className="absolute -right-1 -top-1 h-8 w-8 border-r-4 border-t-4 border-teal-light" /><View className="absolute -bottom-1 -left-1 h-8 w-8 border-b-4 border-l-4 border-teal-light" /><View className="absolute -bottom-1 -right-1 h-8 w-8 border-b-4 border-r-4 border-teal-light" /></View><Text className="mt-6 px-8 text-center text-base font-semibold text-white">Place the authorized QR invite inside the frame</Text>{error ? <View className="mx-7 mt-4 rounded-xl bg-red-600/90 px-4 py-3"><Text className="text-center text-sm font-semibold text-white">{error}</Text></View> : null}</View><View className="px-7 pb-8"><Pressable accessibilityRole="button" accessibilityLabel={scanned || error ? 'Scan again' : 'Cancel scanner'} className="items-center" onPress={() => { setScanned(false); setError(''); }}><Text className="text-sm font-semibold text-white">{scanned || error ? 'Scan again' : 'Cancel'}</Text></Pressable></View></SafeAreaView></CameraView></View>;
}
