import { Calendar, CheckCircle2, ChevronDown, MapPin } from 'lucide-react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import { Button } from '@/components/Button';
import { PhotoPickerField } from '@/components/PhotoPickerField';
import type { EvidenceType } from '@/services/reporting';

export default function SessionEntryScreen() {
  const router = useRouter();
  const { kind = 'note' } = useLocalSearchParams<{ kind?: string }>();
  const [value, setValue] = useState('');
  const [photoUri, setPhotoUri] = useState<string>();
  const [type, setType] = useState<EvidenceType>('OBSERVATION');
  const [location, setLocation] = useState('');
  const [time, setTime] = useState('');
  const [source, setSource] = useState('');
  const [success, setSuccess] = useState(false);
  const isEvidence = kind === 'evidence';
  const isSighting = kind === 'sighting';
  const title = isEvidence ? 'Report Evidence' : isSighting ? 'Report Possible Sighting' : 'Add Search Note';
  if (success) return <SafeAreaView className="flex-1 bg-background"><View className="flex-1 items-center justify-center px-7"><View className="h-16 w-16 items-center justify-center rounded-full bg-green-50"><CheckCircle2 stroke="#16A34A" size={34} /></View><Text className="mt-5 text-2xl font-bold text-navy">{isSighting ? 'Possible sighting saved' : isEvidence ? 'Evidence prepared' : 'Note prepared'}</Text><Text className="mt-3 text-center text-base leading-6 text-muted">This entry is ready for the future backend submission. It is not confirmed by AI.</Text><View className="mt-7 w-full"><Button label="Back to Search" fullWidth onPress={() => router.back()} /></View></View></SafeAreaView>;
  return <SafeAreaView className="flex-1 bg-background"><KeyboardAvoidingView className="flex-1" behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerClassName="px-6 pb-8" keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><Text className="pt-7 text-3xl font-bold text-navy">{title}</Text><Text className="mt-2 text-base leading-6 text-muted">Use factual language. All possible matches require human verification.</Text>{isEvidence ? <Section title="Evidence"><SelectField label="Type" value={type} onPress={() => setType(type === 'OBSERVATION' ? 'WITNESS' : 'OBSERVATION')} /><Field label="Location" placeholder="Where was this observed?" icon={MapPin} value={location} onChangeText={setLocation} /><Field label="Time" placeholder="When did this occur?" icon={Calendar} value={time} onChangeText={setTime} /><Field label="Description" placeholder="Describe only what was observed." multiline value={value} onChangeText={setValue} /><PhotoPickerField value={photoUri} onChange={setPhotoUri} /><Field label="Source (optional)" placeholder="Volunteer, witness, or other permitted source" value={source} onChangeText={setSource} /></Section> : isSighting ? <Section title="Possible Sighting"><Field label="Location" placeholder="Where did you see them?" icon={MapPin} value={location} onChangeText={setLocation} /><Field label="Time" placeholder="When did you see them?" icon={Calendar} value={time} onChangeText={setTime} /><Field label="Description" placeholder="Example: I saw a child wearing a blue shirt moving toward the parking area." multiline value={value} onChangeText={setValue} /><PhotoPickerField value={photoUri} onChange={setPhotoUri} /><Field label="Additional Observation" placeholder="Anything else relevant?" multiline value={source} onChangeText={setSource} /></Section> : <Section title="Search Note"><Field label="Text" placeholder="Write clear, factual details..." multiline value={value} onChangeText={setValue} /><PhotoPickerField value={photoUri} onChange={setPhotoUri} /><Field label="Location (optional)" placeholder="Current zone or nearby landmark" icon={MapPin} value={location} onChangeText={setLocation} /></Section>}<View className="mt-7"><Button label={isSighting ? 'Report Sighting' : isEvidence ? 'Prepare Evidence' : 'Save Search Note'} fullWidth disabled={!value.trim()} onPress={() => setSuccess(true)} /></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View className="mt-7 gap-4"><Text className="text-lg font-bold text-navy">{title}</Text>{children}</View>; }
function Field({ label, placeholder, value, onChangeText, multiline = false, icon: Icon }: { label: string; placeholder: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; icon?: typeof MapPin }) { return <View className="gap-2"><Text className="text-sm font-semibold text-navy">{label}</Text><View className={`flex-row rounded-xl border border-border bg-surface px-4 ${multiline ? 'min-h-[120px]' : 'min-h-[52px] items-center'}`}>{Icon ? <Icon stroke="#64748B" size={18} /> : null}<TextInput accessibilityLabel={label} multiline={multiline} textAlignVertical={multiline ? 'top' : 'center'} className={`flex-1 px-2 py-3 text-base text-navy ${multiline ? 'min-h-[110px]' : ''}`} placeholder={placeholder} placeholderTextColor="#64748B" value={value} onChangeText={onChangeText} /></View></View>; }
function SelectField({ label, value, onPress }: { label: string; value: string; onPress: () => void }) { return <View className="gap-2"><Text className="text-sm font-semibold text-navy">{label}</Text><Pressable accessibilityRole="button" className="min-h-[52px] flex-row items-center justify-between rounded-xl border border-border bg-surface px-4" onPress={onPress}><Text className="text-base text-navy">{value.replace('_', ' ')}</Text><ChevronDown stroke="#64748B" size={19} /></Pressable></View>; }
