import { AlertTriangle, BarChart3, Check, Clock3, Eye, Flag, Info, MessageSquareWarning, ShieldCheck, X } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis, Area, AreaChart } from 'recharts';
import PriorityBadge from '../components/PriorityBadge';
import SectionCard from '../components/SectionCard';
import { aiPriorityItems, confidenceTrend, priorityDistribution } from '../data/aiPriority';
import type { AIPriorityLevel, HumanReviewStatus } from '../data/aiPriority';

const priorityColors: Record<AIPriorityLevel, string> = { Critical: '#DC2626', High: '#F97316', Medium: '#F59E0B', Low: '#0D9488' };
const reviewStyles: Record<HumanReviewStatus, string> = { 'Needs review': 'bg-amber-50 text-amber-700 border-amber-200', Reviewed: 'bg-teal/10 text-teal border-teal/20', 'Accepted for planning': 'bg-blue/10 text-blue border-blue/20', 'Verification requested': 'bg-violet-50 text-violet-700 border-violet-200', Rejected: 'bg-slate-100 text-slate-600 border-slate-200' };

function ReviewBadge({ status }: { status: HumanReviewStatus }) {
  return <span className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-semibold ${reviewStyles[status]}`}>{status}</span>;
}

export default function AIPriorityPage() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-500">Intelligence support</p><h1 className="mt-2 text-3xl font-semibold text-navy">AI-Assisted Search Priority</h1><p className="mt-2 text-sm text-slate-500">Review model-generated signals alongside human operational judgment.</p></div><div className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-soft">Mock model output • Human review required</div></div>

      <div className="flex items-start gap-3 rounded-2xl border border-blue/20 bg-blue/5 p-4 text-blue"><Info size={19} className="mt-0.5 shrink-0" /><div><p className="text-sm font-semibold">AI-assisted priority is decision support.</p><p className="mt-1 text-sm leading-6">AI-assisted priority is decision support. It does not confirm a person's location or identity.</p></div></div>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Needs human review', aiPriorityItems.filter((item) => item.reviewStatus === 'Needs review').length, 'text-amber-700'], ['Critical priority', aiPriorityItems.filter((item) => item.priority === 'Critical').length, 'text-red-600'], ['Avg. confidence', `${Math.round(aiPriorityItems.reduce((sum, item) => sum + item.confidence, 0) / aiPriorityItems.length)}%`, 'text-blue'], ['Accepted for planning', aiPriorityItems.filter((item) => item.reviewStatus === 'Accepted for planning').length, 'text-teal']].map(([label, value, color]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><p className="text-sm text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${color}`}>{value}</p></div>)}</section>

      <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]"><SectionCard title="Priority distribution" subtitle="Mock model signals" action={<BarChart3 size={18} className="text-blue" />}><div className="h-64"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={priorityDistribution} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} paddingAngle={4}>{priorityDistribution.map((item) => <Cell key={item.name} fill={priorityColors[item.name as AIPriorityLevel]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="mt-3 grid grid-cols-2 gap-2">{priorityDistribution.map((item) => <div key={item.name} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="flex items-center gap-2 text-slate-600"><i className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: priorityColors[item.name as AIPriorityLevel] }} />{item.name}</span><span className="font-semibold text-slate-900">{item.value}</span></div>)}</div></SectionCard><SectionCard title="Confidence and review trend" subtitle="Informational only" action={<Clock3 size={18} className="text-slate-500" />}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={confidenceTrend}><defs><linearGradient id="confidence" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#2563EB" stopOpacity={0.25} /><stop offset="100%" stopColor="#2563EB" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid stroke="#E2E8F0" strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 12 }} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fill: '#64748B', fontSize: 12 }} /><Tooltip /><Area type="monotone" dataKey="confidence" stroke="#2563EB" strokeWidth={2} fill="url(#confidence)" name="Confidence %" /><Area type="monotone" dataKey="reviewed" stroke="#0D9488" strokeWidth={2} fill="transparent" name="Human reviews" /></AreaChart></ResponsiveContainer></div><p className="mt-2 text-xs text-slate-500">Trend values describe model and review activity; they are not location certainty.</p></SectionCard></section>

      <SectionCard title="AI priority queue" subtitle="Review before planning"><div className="space-y-4">{aiPriorityItems.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wide text-blue">{item.id}</span><PriorityBadge priority={item.priority} /><ReviewBadge status={item.reviewStatus} /></div><div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm"><span className="font-semibold text-slate-900">{item.caseId}</span><span className="text-slate-500">{item.zone}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-[11px] uppercase tracking-wide text-slate-500">AI confidence</p><p className="mt-1 text-lg font-semibold text-navy">{item.confidence}%</p><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full" style={{ width: `${item.confidence}%`, backgroundColor: priorityColors[item.priority] }} /></div></div><div><p className="text-[11px] uppercase tracking-wide text-slate-500">Last updated</p><p className="mt-1 text-sm font-semibold text-slate-800">{item.lastUpdated}</p></div><div className="sm:col-span-2"><p className="text-[11px] uppercase tracking-wide text-slate-500">Supporting factors</p><div className="mt-1 flex flex-wrap gap-1.5">{item.supportingFactors.map((factor) => <span key={factor} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] text-slate-600">{factor}</span>)}</div></div></div></div><div className="flex shrink-0 flex-wrap gap-2 xl:max-w-[330px] xl:justify-end"><button className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-blue hover:text-blue"><Eye size={14} /> Review</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-blue/20 bg-blue/5 px-3 py-2 text-xs font-semibold text-blue hover:bg-blue/10"><Check size={14} /> Accept for planning</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-red-200 hover:text-red-600"><X size={14} /> Reject</button><button className="inline-flex items-center gap-1.5 rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700 hover:bg-violet-100"><MessageSquareWarning size={14} /> Request human verification</button></div></div></article>)}</div></SectionCard>

      <div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-800"><AlertTriangle size={18} className="mt-0.5 shrink-0" /><p className="text-sm leading-6"><strong>Human review remains authoritative.</strong> These actions only demonstrate the future review workflow. AI output must not be treated as confirmed location or identity information.</p></div>
    </div>
  );
}
