import { AlertTriangle, Bell, Check, CheckCheck, CircleDot, Clock3, Info, Search, ShieldAlert, UserRound, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import SectionCard from '../components/SectionCard';
import { notifications, notificationTypes } from '../data/notificationsSettings';
import type { AdminNotification, NotificationType } from '../data/notificationsSettings';

const icons: Record<NotificationType, typeof Bell> = { 'Critical alert': AlertTriangle, 'New sighting': CircleDot, 'Volunteer update': UserRound, 'AI priority update': Info, 'Possible match': Search, Escalation: ShieldAlert, 'System notification': Bell };
const tones: Record<NotificationType, string> = { 'Critical alert': 'bg-red-50 text-red-600', 'New sighting': 'bg-blue/10 text-blue', 'Volunteer update': 'bg-teal/10 text-teal', 'AI priority update': 'bg-violet-50 text-violet-700', 'Possible match': 'bg-amber-50 text-amber-700', Escalation: 'bg-red-50 text-red-600', 'System notification': 'bg-slate-100 text-slate-600' };

export default function NotificationsPage() {
  const [items, setItems] = useState(notifications);
  const [filter, setFilter] = useState<'All' | NotificationType>('All');
  const [query, setQuery] = useState('');
  const visible = useMemo(() => items.filter((item) => { const value = query.toLowerCase().trim(); return (filter === 'All' || item.type === filter) && (!value || item.title.toLowerCase().includes(value) || item.detail.toLowerCase().includes(value) || item.caseId?.toLowerCase().includes(value)); }), [items, filter, query]);
  const unread = items.filter((item) => !item.read).length;
  const markRead = (id: string) => setItems((current) => current.map((item) => item.id === id ? { ...item, read: true } : item));

  return <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-500">Command center</p><h1 className="mt-2 text-3xl font-semibold text-navy">Notifications</h1><p className="mt-2 text-sm text-slate-500">Keep up with safety, case, field, intelligence, and system activity.</p></div><div className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-soft">{unread} unread</div></div><SectionCard title="Notification inbox" subtitle="Operational updates" action={<button onClick={() => setItems((current) => current.map((item) => ({ ...item, read: true })))} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:text-blue"><CheckCheck size={15} /> Mark all as read</button>}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 text-slate-500 lg:max-w-md"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notifications" className="w-full bg-transparent text-sm outline-none placeholder:text-slate-400" /></label><select value={filter} onChange={(event) => setFilter(event.target.value as 'All' | NotificationType)} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-xs font-semibold text-slate-600 outline-none"><option value="All">All notification types</option>{notificationTypes.map((type) => <option key={type}>{type}</option>)}</select></div><div className="mt-5 space-y-3">{visible.map((item) => <NotificationRow key={item.id} item={item} onRead={() => markRead(item.id)} />)}{visible.length === 0 ? <div className="py-10 text-center text-sm text-slate-500">No notifications match this filter.</div> : null}</div></SectionCard></div>;
}

function NotificationRow({ item, onRead }: { item: AdminNotification; onRead: () => void }) {
  const Icon = icons[item.type];
  return <div className={`flex items-start gap-4 rounded-xl border p-4 transition ${item.read ? 'border-slate-200 bg-white' : 'border-blue/20 bg-blue/5'}`}><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${tones[item.type]}`}><Icon size={18} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{item.title}</p>{!item.read ? <span className="rounded-full bg-blue px-2 py-0.5 text-[10px] font-bold uppercase text-white">New</span> : null}</div><p className="mt-1 text-sm leading-6 text-slate-600">{item.detail}</p><div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-slate-500"><span className="flex items-center gap-1"><Clock3 size={13} />{item.time}</span><span>{item.type}</span>{item.caseId ? <span className="font-semibold text-blue">{item.caseId}</span> : null}</div></div><button onClick={onRead} disabled={item.read} aria-label={item.read ? 'Already read' : `Mark ${item.id} as read`} className="rounded-lg border border-slate-200 p-2 text-slate-500 enabled:hover:text-blue disabled:opacity-40"><Check size={16} /></button></div>;
}
