import { CheckCircle2, Expand, Eye, Layers3, MapPin, RefreshCw, Search, Send, Users, UserRoundPlus, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import PriorityBadge from '../components/PriorityBadge';
import SectionCard from '../components/SectionCard';
import StatusBadge from '../components/StatusBadge';
import ZoneAllocationPlaceholder from '../components/ZoneAllocationPlaceholder';
import { searchZones } from '../data/searchZones';
import type { SearchZoneStatus } from '../data/searchZones';

const statuses: Array<'All' | SearchZoneStatus> = ['All', 'Unassigned', 'Assigned', 'Searching', 'Completed', 'Expanded', 'Cancelled'];

export default function SearchZonesPage() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<(typeof statuses)[number]>('All');
  const [selectedId, setSelectedId] = useState<string | null>(searchZones[0].id);
  const selectedZone = searchZones.find((zone) => zone.id === selectedId) ?? searchZones[0];
  const visibleZones = useMemo(() => searchZones.filter((zone) => {
    const normalizedQuery = query.toLowerCase().trim();
    return (status === 'All' || zone.status === status) && (!normalizedQuery || zone.id.toLowerCase().includes(normalizedQuery) || zone.caseId.toLowerCase().includes(normalizedQuery) || zone.assignedTeam.toLowerCase().includes(normalizedQuery));
  }), [query, status]);

  return (
    <div className="space-y-6"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-500">Intelligence operations</p><h1 className="mt-2 text-3xl font-semibold text-navy">Search Zone Management</h1><p className="mt-2 text-sm text-slate-500">Allocate field coverage and monitor progress across active search zones.</p></div><div className="rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600 shadow-soft">UI-only mock workspace</div></div>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total zones', searchZones.length, 'text-navy'], ['Searching', searchZones.filter((zone) => zone.status === 'Searching').length, 'text-blue'], ['Unassigned', searchZones.filter((zone) => zone.status === 'Unassigned').length, 'text-amber-700'], ['Overlap warnings', searchZones.filter((zone) => zone.overlapsWith).length / 2, 'text-red-600']].map(([label, value, color]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><p className="text-sm text-slate-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${color}`}>{value}</p></div>)}</section>

      <section className="grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><SectionCard title="Visual zone allocation" subtitle="Placeholder visualization" action={<div className="flex items-center gap-2 text-xs text-slate-500"><RefreshCw size={14} /> Updated 2 min ago</div>}><ZoneAllocationPlaceholder zones={visibleZones} selectedId={selectedZone.id} onSelect={setSelectedId} /></SectionCard><SectionCard title="Selected zone" subtitle="Allocation details"><div className="space-y-4"><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-semibold text-navy">{selectedZone.id}</p><p className="mt-1 text-sm text-slate-500">{selectedZone.caseId}</p></div><StatusBadge status={selectedZone.status} /></div><div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><Users size={16} className="text-blue" /> {selectedZone.assignedTeam}</div><div className="mt-3 flex items-center gap-2 text-sm text-slate-600"><MapPin size={16} className="text-teal" /> Zone allocation preview</div></div><div><div className="mb-2 flex justify-between text-sm"><span className="text-slate-600">Progress</span><span className="font-semibold text-navy">{selectedZone.progress}%</span></div><div className="h-2.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue to-teal" style={{ width: `${selectedZone.progress}%` }} /></div></div><p className="text-xs text-slate-500">Last update: {selectedZone.lastUpdate}</p></div></SectionCard></section>

      {searchZones.some((zone) => zone.overlapsWith) ? <div className="flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-800"><Layers3 size={18} className="mt-0.5 shrink-0" /><div><p className="text-sm font-semibold">Zone overlap warning</p><p className="mt-1 text-sm">ZONE-041 and ZONE-044 appear to overlap. Review team boundaries before expanding coverage.</p></div></div> : null}

      <SectionCard title="Search zones" subtitle="Zone registry"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><label className="flex min-h-11 flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 text-slate-500 lg:max-w-md"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search zone ID, case, or team" className="w-full bg-transparent text-sm outline-none placeholder:text-slate-400" /></label><div className="flex gap-2 overflow-x-auto pb-1">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-semibold ${status === item ? 'bg-navy text-white' : 'border border-slate-200 bg-white text-slate-600'}`}>{item}</button>)}</div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[980px] w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500">{['Zone ID', 'Case', 'Assigned team', 'Status', 'Priority', 'Progress', 'Last update', ''].map((heading) => <th key={heading} className="pb-3 pr-4 font-medium">{heading}</th>)}</tr></thead><tbody>{visibleZones.map((zone) => <tr key={zone.id} className={`border-b border-slate-100 last:border-0 ${selectedZone.id === zone.id ? 'bg-blue/5' : ''}`}><td className="py-4 pr-4 font-semibold text-blue">{zone.id}</td><td className="py-4 pr-4 font-medium text-slate-900">{zone.caseId}</td><td className="py-4 pr-4 text-slate-600">{zone.assignedTeam}</td><td className="py-4 pr-4"><StatusBadge status={zone.status} /></td><td className="py-4 pr-4"><PriorityBadge priority={zone.priority} /></td><td className="py-4 pr-4"><div className="flex items-center gap-2"><div className="h-2 w-20 rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal" style={{ width: `${zone.progress}%` }} /></div><span className="text-xs font-semibold text-slate-700">{zone.progress}%</span></div></td><td className="py-4 pr-4 text-slate-500">{zone.lastUpdate}</td><td className="py-4"><button onClick={() => setSelectedId(zone.id)} aria-label={`View ${zone.id}`} className="inline-flex rounded-lg border border-slate-200 p-2 text-slate-600 hover:text-blue"><Eye size={16} /></button></td></tr>)}</tbody></table></div></SectionCard>

      <SectionCard title="Zone controls" subtitle="UI-only actions"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><button className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-left text-sm font-semibold text-slate-700 hover:border-blue hover:text-blue">Assign team <UserRoundPlus size={16} /></button><button className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-left text-sm font-semibold text-slate-700 hover:border-blue hover:text-blue">Reassign team <Users size={16} /></button><button className="flex items-center justify-between rounded-xl border border-teal/20 bg-teal/5 p-3 text-left text-sm font-semibold text-teal hover:bg-teal/10">Mark completed <CheckCircle2 size={16} /></button><button className="flex items-center justify-between rounded-xl border border-amber-200 bg-amber-50 p-3 text-left text-sm font-semibold text-amber-700 hover:bg-amber-100">Expand zone <Expand size={16} /></button><button className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-left text-sm font-semibold text-slate-700 hover:border-blue hover:text-blue">View activity <Eye size={16} /></button></div><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><Send size={14} /> Controls are visual placeholders and do not mutate backend data.</p></SectionCard>
    </div>
  );
}
