from enum import StrEnum


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    CASE_MANAGER = "CASE_MANAGER"
    VOLUNTEER = "VOLUNTEER"
    REPORTER = "REPORTER"


class CaseStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    LOCAL_SEARCH = "LOCAL_SEARCH"
    LOCAL_SEARCH_COMPLETED = "LOCAL_SEARCH_COMPLETED"
    PUBLIC_ESCALATION_PENDING = "PUBLIC_ESCALATION_PENDING"
    PUBLIC_SEARCH = "PUBLIC_SEARCH"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class CasePriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
