import { ArrowDown, ArrowUp, Minus, Sparkles } from 'lucide-react-native';
import { Text, View } from 'react-native';
import type { AIPriorityResult } from '@/services/aiPriority';
import { Card } from './Card';

export function AIPriorityCard({ result }: { result: AIPriorityResult }) {
  const change = result.change === 'UP' ? <ArrowUp stroke="#16A34A" size={14} /> : result.change === 'DOWN' ? <ArrowDown stroke="#DC2626" size={14} /> : <Minus stroke="#64748B" size={14} />;
  const changeText = result.previousPriority === undefined || result.change === 'UNCHANGED' ? 'No change' : `${Math.abs(result.priority - result.previousPriority)} pts`;
  return <Card className="overflow-hidden"><View className="flex-row items-start justify-between gap-3"><View className="flex-row items-center gap-3"><View className="h-10 w-10 items-center justify-center rounded-xl bg-navy"><Sparkles stroke="#5EEAD4" size={19} /></View><View><Text className="text-lg font-bold text-navy">{result.zoneId}</Text><Text className="mt-1 text-xs text-muted">AI-assisted decision support</Text></View></View><View className="items-end"><Text className="text-2xl font-bold text-navy">{result.priority}</Text><Text className="text-xs text-muted">Priority</Text></View></View><View className="mt-5 h-3 overflow-hidden rounded-full bg-background-muted"><View className={`h-full rounded-full ${result.priority >= 80 ? 'bg-danger' : result.priority >= 60 ? 'bg-warning' : 'bg-blue'}`} style={{ width: `${result.priority}%` }} /></View><View className="mt-3 flex-row items-center justify-between"><View className="flex-row items-center gap-1"><View className="flex-row items-center gap-1 rounded-full bg-background-muted px-2 py-1">{change}<Text className="text-xs font-semibold text-muted">{changeText}</Text></View>{result.previousPriority !== undefined ? <Text className="text-xs text-muted">from {result.previousPriority}</Text> : null}</View><Text className="text-xs text-muted">{result.updatedAt}</Text></View><View className="mt-4 flex-row flex-wrap gap-2">{result.reasons.map((reason) => <View key={reason} className="rounded-full bg-blue-50 px-3 py-1.5"><Text className="text-xs font-medium text-blue">{reason}</Text></View>)}</View></Card>;
}
