import { Hospital, MapPin, ParkingSquare, Shield, TrainFront, UserRound } from 'lucide-react-native';
import { Text, View } from 'react-native';
import type { MapLayer } from '@/services/map';

const layerLabels: Record<MapLayer, string> = { LAST_SEEN_LOCATION: 'Last seen', SEARCH_BOUNDARY: 'Boundary', SEARCH_ZONES: 'Search zones', VOLUNTEER_LOCATION: 'Volunteer', EXITS: 'Exits', ROADS: 'Roads', PARKING: 'Parking', TRANSPORT_NODES: 'Transport', HOSPITALS: 'Hospitals', POLICE_STATIONS: 'Police', SAFE_POINTS: 'Safe points' };
const layerIcons = { LAST_SEEN_LOCATION: MapPin, VOLUNTEER_LOCATION: UserRound, PARKING: ParkingSquare, TRANSPORT_NODES: TrainFront, HOSPITALS: Hospital, POLICE_STATIONS: Shield } as const;

export function MapPlaceholder({ layers }: { layers: MapLayer[] }) {
  return <View className="overflow-hidden rounded-2xl border border-border bg-[#EAF2F4]"><View className="h-[270px] overflow-hidden"><View className="absolute left-[-30px] top-24 h-5 w-[120%] rotate-[18deg] bg-white/80" /><View className="absolute left-[-20px] top-36 h-3 w-[120%] -rotate-[32deg] bg-white/80" /><View className="absolute left-20 top-[-40px] h-[380px] w-4 rotate-[42deg] bg-white/80" /><View className="absolute left-44 top-[-40px] h-[380px] w-3 -rotate-[18deg] bg-white/80" /><View className="absolute left-16 top-16 h-36 w-64 rounded-[80px] border-2 border-dashed border-blue/60 bg-blue-50/40" /><View className="absolute left-24 top-24 h-4 w-4 rounded-full border-2 border-white bg-danger" /><View className="absolute right-24 top-28 h-4 w-4 rounded-full border-2 border-white bg-blue" /><View className="absolute bottom-20 left-36 h-4 w-4 rounded-full border-2 border-white bg-teal" /><View className="absolute bottom-6 left-0 right-0 items-center"><View className="rounded-full bg-navy/90 px-4 py-2"><Text className="text-xs font-semibold text-white">Map interface placeholder</Text></View></View></View><View className="flex-row flex-wrap gap-2 border-t border-border bg-surface p-4">{layers.map((layer) => { const Icon = layerIcons[layer as keyof typeof layerIcons]; return <View key={layer} className="flex-row items-center gap-1.5 rounded-full bg-background-muted px-2.5 py-1.5">{Icon ? <Icon stroke="#2563EB" size={13} /> : <View className="h-2 w-2 rounded-full bg-teal" />}<Text className="text-xs font-medium text-muted">{layerLabels[layer]}</Text></View>; })}</View></View>;
}
