import { Bell, Camera, CheckCircle2, LocateFixed, XCircle } from 'lucide-react-native';
import { ActivityIndicator, Pressable, Text, View } from 'react-native';

export type PermissionKind = 'location' | 'camera' | 'notifications';
export type PermissionState = 'not-requested' | 'requesting' | 'granted' | 'denied' | 'blocked';

type PermissionCardProps = { kind: PermissionKind; state: PermissionState; onRequest?: () => void };
const details = { location: { title: 'Location permission', reason: 'Location helps record your search activity and keep your assigned search zone accurate.', icon: LocateFixed }, camera: { title: 'Camera permission', reason: 'Camera access is needed to scan case QR codes and optionally attach evidence.', icon: Camera }, notifications: { title: 'Notification permission', reason: 'Notifications keep you informed about assignments, sightings and critical case updates.', icon: Bell } } as const;

export function PermissionCard({ kind, state, onRequest }: PermissionCardProps) { const item = details[kind]; const Icon = item.icon; const requestable = state === 'not-requested' || state === 'denied'; const blocked = state === 'blocked'; return <View className="rounded-2xl border border-border bg-surface p-4 shadow-sm"><View className="flex-row items-start gap-3"><View className="rounded-xl bg-blue-50 p-2.5"><Icon stroke="#2563EB" size={21} /></View><View className="flex-1"><Text className="text-base font-bold text-navy">{item.title}</Text><Text className="mt-2 text-sm leading-5 text-muted">{item.reason}</Text></View></View><View className="mt-4 flex-row items-center justify-between"><View className="flex-row items-center gap-2">{state === 'requesting' ? <ActivityIndicator color="#2563EB" size="small" /> : state === 'granted' ? <CheckCircle2 stroke="#16A34A" size={17} /> : state === 'blocked' || state === 'denied' ? <XCircle stroke="#DC2626" size={17} /> : null}<Text className={`text-xs font-semibold ${state === 'granted' ? 'text-success' : state === 'blocked' || state === 'denied' ? 'text-danger' : 'text-muted'}`}>{state.replace('-', ' ')}</Text></View>{requestable ? <Pressable accessibilityRole="button" className="rounded-lg bg-blue px-3 py-2 active:opacity-80" onPress={onRequest}><Text className="text-xs font-semibold text-white">Allow</Text></Pressable> : blocked ? <Text className="text-xs font-semibold text-danger">Enable in Settings</Text> : null}</View></View>; }
